src/InvoiceMakerPro/Controllers/ArticlesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using InvoiceMakerPro.Models;
using System;
using Microsoft.AspNet.Authorization;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace InvoiceMakerPro.Controllers
{
    [Authorize]
    public class ArticlesController : Controller
    {
        private ApplicationDbContext _context;

        public ArticlesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Articles
        public IActionResult Index()
        {
            return View(_context.Article.ToList());
        }

        // GET: Articles/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Article article = _context.Article.Single(m => m.ArticleId == id);
            if (article == null)
            {
                return HttpNotFound();
            }

            return View(article);
        }

        // GET: Articles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Articles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Article article)
        {
            if (ModelState.IsValid)
            {
                article.ArticleId = Guid.NewGuid();
                _context.Article.Add(article);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Articles/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Article article = _context.Article.Single(m => m.ArticleId == id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Articles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Article article)
        {
            if (ModelState.IsValid)
            {
                _context.Update(article);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Articles/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Article article = _context.Article.Single(m => m.ArticleId == id);
            if (article == null)
            {
                return HttpNotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            Article article = _context.Article.Single(m => m.ArticleId == id);
            _context.Article.Remove(article);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult GetArticles([DataSourceRequest]DataSourceRequest request)
        {
            return Json(_context.Article.ToDataSourceResult(request));
        }
    }
}

src/InvoiceMakerPro/Controllers/InvoicesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using InvoiceMakerPro.Models;
using System;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace InvoiceMakerPro.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<InvoicesController> _logger;
        private readonly IConfiguration _config;

        public InvoicesController(ApplicationDbContext context, ILogger<InvoicesController> logger, IConfiguration config)
        {
            _context = context;
            _logger = logger;
            _config = config;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetInvoices()
        {
            try
            {
                var model =
                    _context.Invoice.Include(i => i.Customer).Include(i => i.Store)
                        .Include(i => i.InvoiceDetails)
                        .ThenInclude(p => p.Article)
                        .ToList();
                return Json(model);
            }
            catch (Exception ex)
            {
                _logger.LogInformation($"{ex.Message}{Environment.NewLine}{ex.InnerException}");
            }

            return null;
        }

        public JsonResult GetCustomerInvoices(Guid CustomerId)
        {
            try
            {
                var model =
                    _context.Invoice.Include(i => i.Customer).Where(i => i.Customer.CustomerId == CustomerId)
                        .Include(i => i.InvoiceDetails)
                        .ThenInclude(p => p.Article)
                        .ToList();
                return Json(model);
            }
            catch (Exception ex)
            {
                _logger.LogInformation($"{ex.Message}{Environment.NewLine}{ex.InnerException}");
            }

            return null;
        }

        public void DeleteInvoice(Guid InvoiceId)
        {
            var invoice = _context.Invoice.Include(i => i.InvoiceDetails).FirstOrDefault(i => i.InvoiceId == InvoiceId);
            if (invoice != null)
            {
                _context.InvoiceDetails.RemoveRange(invoice.InvoiceDetails);
                _context.Invoice.Remove(invoice);

                _context.SaveChanges();
            }
        }

        public void ReleaseInvoice(Guid InvoiceId)
        {
            var invoice = _context.Invoice.FirstOrDefault(i => i.InvoiceId == InvoiceId);
            if (invoice != null)
            {
                invoice.InvoiceState = InvoiceState.Released;
                _context.Entry(invoice).State = EntityState.Modified;

                _context.SaveChanges();
            }
        }

        public ActionResult EditInvoice(Guid id)
        {
            if (id == Guid.Empty)
            {
                var max = _context.Invoice.ToList().Max(f => f.InvoiceNumber);

                return View(new Invoice
                {
                    InvoiceId = Guid.Empty,
                    InvoiceNumber = (max ?? 0) + 1
                });
            }
            else
            {
                var model = _context.Invoice.Include(i => i.Customer).Include(i => i.Store).Include(i => i.InvoiceDetails).ThenInclude(p => p.Article).FirstOrDefault(i => i.InvoiceId == id);
                foreach (var detail in model.InvoiceDetails)
                {
                    detail.Invoice = null;
                }
                return View(model);
            }
        }

        [HttpPost]
        public JsonResult SaveInvoice([FromBody] Invoice invoice)
        {
            try
            {
                if (invoice.Customer == null)
                    throw new Exception("Please select a Customer.");

                if (invoice.Store == null)
                    throw new Exception("Please select a Store.");

                var cleanList = invoice.InvoiceDetails.ToList();
                cleanList.RemoveAll(article => article.Article == null);
                invoice.InvoiceDetails = cleanList;

                if (invoice.InvoiceDetails == null || invoice.InvoiceDetails.Count == 0)
                    throw new Exception("Please select at least one article.");

                var attachedEntity = _context.Invoice.SingleOrDefault(i => i.InvoiceId == invoice.InvoiceId);
                if (attachedEntity != null)
                {
                    DeleteInvoice(invoice.InvoiceId);
                }

                _context.Invoice.Add(invoice);

                invoice.User = User.Identity.Name;
                _context.SaveChanges();
                return Json(new { success = true, id = invoice.InvoiceId });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        public ActionResult Print(Guid id)
        {
            ViewBag.Print = true;
            var companyInfo = _config.GetSection("CompanyInfo").GetChildren();
            ViewBag.MyCompany = companyInfo.FirstOrDefault(k => k.Key == "MyCompanyName")?.Value;
            ViewBag.MyCompanyID = companyInfo.FirstOrDefault(k => k.Key == "MyCompanyID")?.Value;
            ViewBag.MyCompanyAddress = companyInfo.FirstOrDefault(k => k.Key == "MyCompanyAddress")?.Value;
            ViewBag.MyCompanyPhone = companyInfo.FirstOrDefault(k => k.Key == "MyCompanyPhone")?.Value;
            ViewBag.MyEmail = companyInfo.FirstOrDefault(k => k.Key == "MyEmail")?.Value;
            ViewBag.MyBankAccount = companyInfo.FirstOrDefault(k => k.Key == "MyBankAccount")?.Value;

            Invoice invoice = _context.Invoice.Include(i => i.Customer).Include(i => i.InvoiceDetails).ThenInclude(p => p.Article).FirstOrDefault(i => i.InvoiceId == id);
            return View(invoice);
        }
    }
}

src/InvoiceMakerPro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InvoiceMakerPro</title>

    <!--CSS-->
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        @*<link rel="stylesheet" href="~/lib/kendo/css/kendo.common.min.css" />
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2016.2.504/styles/kendo.blueopal.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/css/kendo.dataviz.min.css" />
        <link rel="stylesheet" href="~/lib/kendo/css/kendo.dataviz.bootstrap.min.css" />*@
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2016.2.504/styles/kendo.common.min.css" />
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2016.2.504/styles/kendo.blueopal.min.css" />
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2016.2.504/styles/kendo.dataviz.min.css" />
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2016.2.504/styles/kendo.dataviz.bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css" asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2016.2.504/styles/kendo.common.min.css" asp-fallback-href="~/lib/kendo/css/kendo.common.min.css" />
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2016.2.504/styles/kendo.blueopal.min.css" asp-fallback-href="~/lib/kendo/css/kendo.blueopal.min.css" />
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2016.2.504/styles/kendo.dataviz.min.css" asp-fallback-href="~/lib/kendo/css/kendo.dataviz.min.css" />
        <link rel="stylesheet" href="http://cdn.kendostatic.com/2016.2.504/styles/kendo.dataviz.bootstrap.min.css" asp-fallback-href="~/lib/kendo/css/kendo.dataviz.bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css" />
    </environment>

    <!--JS-->
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        @*<script src="~/lib/kendo/js/kendo.all.min.js"></script>
        <script src="~/lib/kendo/js/kendo.timezones.min.js"></script>
        <script src="~/lib/kendo/js/kendo.aspnetmvc.min.js"></script>*@
        <script src="http://cdn.kendostatic.com/2016.2.504/js/kendo.all.min.js"></script>
        <script src="http://cdn.kendostatic.com/2016.2.504/js/kendo.timezones.min.js"></script>
        <script src="http://cdn.kendostatic.com/2016.2.504/js/kendo.aspnetmvc.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/gridtabbing.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="http://cdn.kendostatic.com/2016.2.504/js/kendo.all.min.js" asp-fallback-src="~/lib/kendo/js/kendo.all.min.js"></script>
        <script src="http://cdn.kendostatic.com/2016.2.504/js/kendo.timezones.min.js" asp-fallback-src="~/lib/kendo/js/kendo.timezones.min.js"></script>
        <script src="http://cdn.kendostatic.com/2016.2.504/js/kendo.aspnetmvc.min.js" asp-fallback-src="~/lib/kendo/js/kendo.aspnetmvc.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/gridtabbing.min.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <div class="container body-content" id="mainContent">
        @if (User.Identity.IsAuthenticated)
        {
        <div class="margin-top" style="height: 65px;">
            <div class="left-align">
                <a asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" class="minus-margin-top" /></a>
            </div>
            @Html.Partial("_LoginPartial")
        </div>

        <ul id="menu" class="margin-top">
            <li id="InvoicesMenuLink">@Html.ActionLink("My Invoices", "Index", "Invoices")</li>
            <li id="CustomerMenuLink">@Html.ActionLink("Customers", "Index", "Customers")</li>
            <li id="StoreMenuLink">@Html.ActionLink("Stores", "Index", "Stores")</li>
            <li id="ArticleMenuLink">@Html.ActionLink("My Supplies", "Index", "Articles")</li>
        </ul>
        }
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - InvoiceMakerPro</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>

src/InvoiceMakerPro/Views/Shared/_LayoutPrint.cshtml
@using Kendo.Mvc.UI
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="@Url.Content("~/print/style.print.css")" rel="stylesheet" />
    <link href="~/print/bootstrap.extra.css" rel="stylesheet" />
    <link href="~/print/bootstrap.min.css" rel="stylesheet" />
    <link href="~/print/bootstrap.print.css" rel="stylesheet" />
</head>
<body>
    <div class="container-fluid">
        @RenderBody()
    </div>
</body>
</html>