src/InvoiceMakerPro/Models/Store.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace InvoiceMakerPro.Models
{
    public class Store
    {
        public Guid StoreId { get; set; }

        [Required(ErrorMessage = "Name required")]
        [Display(Name = "Name")]
        public string Name { get; set; }
     
        [Required(ErrorMessage = "Address required")]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Zip code required")]
        [Display(Name = "CP")]
        public string CP { get; set; }

        [Required(ErrorMessage = "City required")]
        [Display(Name = "City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Contact person required")]
        [Display(Name = "Contact person")]
        public string ContactPerson { get; set; }

        [Required(ErrorMessage = "Telephone required")]
        [Display(Name = "Telephone")]
        public string Phone1 { get; set; }

        [Display(Name = "Mobile")]
        public string Phone2 { get; set; }

        public string Fax { get; set; }

        [Required(ErrorMessage = "Email required")]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*", ErrorMessage = "Wrong email format")]
        public string Email { get; set; }

        public string Notes { get; set; }

        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}

src/InvoiceMakerPro/Controllers/StoresController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using InvoiceMakerPro.Models;
using System;
using Microsoft.AspNet.Authorization;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace InvoiceMakerPro.Controllers
{
    [Authorize]
    public class StoresController : Controller
    {
        private ApplicationDbContext _context;

        public StoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Stores
        public IActionResult Index()
        {
            return View(_context.Store.ToList());
        }

        // GET: Stores/Details/5
        public IActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Store store = _context.Store.Single(m => m.StoreId == id);
            if (store == null)
            {
                return HttpNotFound();
            }

            return View(store);
        }

        // GET: Stores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Stores/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Store store)
        {
            if (ModelState.IsValid)
            {
                store.StoreId = Guid.NewGuid();
                _context.Store.Add(store);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(store);
        }

        // GET: Stores/Edit/5
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Store store = _context.Store.Single(m => m.StoreId == id);
            if (store == null)
            {
                return HttpNotFound();
            }
            return View(store);
        }

        // POST: Stores/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Store store)
        {
            if (ModelState.IsValid)
            {
                _context.Update(store);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(store);
        }

        // GET: Stores/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Store store = _context.Store.Single(m => m.StoreId == id);
            if (store == null)
            {
                return HttpNotFound();
            }

            return View(store);
        }

        // POST: Stores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            Store store = _context.Store.Single(m => m.StoreId == id);
            _context.Store.Remove(store);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public JsonResult GetStores([DataSourceRequest] DataSourceRequest request)
        {
            return Json(_context.Store.ToDataSourceResult(request));
        }
    }
}

src/InvoiceMakerPro/Views/Stores/Create.cshtml
@model InvoiceMakerPro.Models.Store

@{
    ViewData["Title"] = "New Store";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ul class="breadcrumb">
    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li><a asp-controller="Stores" asp-action="Index">Stores</a></li>
    <li class="active">New Store</li>
</ul>

<form asp-action="Create">
    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CP" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CP" class="form-control" />
                <span asp-validation-for="CP" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ContactPerson" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactPerson" class="form-control" />
                <span asp-validation-for="ContactPerson" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Fax" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone1" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone1" class="form-control" />
                <span asp-validation-for="Phone1" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone2" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone2" class="form-control" />
                <span asp-validation-for="Phone2" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Notes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default k-button k-primary" />
                <a asp-action="Index" class="btn btn-default k-button">Back to List</a>
            </div>
        </div>
    </div>
</form>

src/InvoiceMakerPro/Views/Stores/Delete.cshtml
@model InvoiceMakerPro.Models.Store

@{
    ViewData["Title"] = "Delete Store";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ul class="breadcrumb">
    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li><a asp-controller="Stores" asp-action="Index">Stores</a></li>
    <li class="active">Delete Store</li>
</ul>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactPerson)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactPerson)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone2)
        </dd>
    </dl>

    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default k-button k-primary" />
            <a asp-action="Index" class="btn btn-default k-button">Back to List</a>
        </div>
    </form>
</div>

src/InvoiceMakerPro/Views/Stores/Details.cshtml
@model InvoiceMakerPro.Models.Store

@{
    ViewData["Title"] = "Store Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ul class="breadcrumb">
    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li><a asp-controller="Stores" asp-action="Index">Stores</a></li>
    <li class="active">Details</li>
</ul>

<div>
    <hr />
    <h3>@(Model.Name) Details</h3>
    <dl class="dl-horizontal spaced-lines">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CP)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CP)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContactPerson)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContactPerson)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fax)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fax)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone2)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.StoreId" class="k-button k-primary btn btn-default">Edit</a>
    <a asp-action="Index" class="btn btn-default k-button">Back to List</a>
</p>

src/InvoiceMakerPro/Views/Stores/Edit.cshtml
@model InvoiceMakerPro.Models.Store

@{
    ViewData["Title"] = "Edit Store";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ul class="breadcrumb">
    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li><a asp-controller="Stores" asp-action="Index">Stores</a></li>
    <li class="active">Edit Store</li>
</ul>

<form asp-action="Edit">
    <div class="form-horizontal">
        <hr />
        <h3>@(Model.Name) Details</h3>
        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
        <input type="hidden" asp-for="StoreId" />
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="CP" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="CP" class="form-control" />
                <span asp-validation-for="CP" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ContactPerson" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ContactPerson" class="form-control" />
                <span asp-validation-for="ContactPerson" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Fax" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Fax" class="form-control" />
                <span asp-validation-for="Fax" class="text-danger" />
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Phone1" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone1" class="form-control" />
                <span asp-validation-for="Phone1" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone2" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone2" class="form-control" />
                <span asp-validation-for="Phone2" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Notes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Notes" class="form-control" />
                <span asp-validation-for="Notes" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default k-button k-primary" />
                <a asp-action="Index" class="btn btn-default k-button">Back to List</a>
            </div>
        </div>

    </div>
</form>

src/InvoiceMakerPro/Views/Stores/Index.cshtml
@model IEnumerable<InvoiceMakerPro.Models.Store>

@{
    ViewData["Title"] = "Stores";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<ul class="breadcrumb">
    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
    <li class="active" style="color: black">Stores</li>
</ul>

<p>
    @(Html.ActionLink("Add New", "Create", "Stores", htmlAttributes: new { @class = "k-primary k-button btn btn-primary" }))
</p>

@(Html.Kendo().Grid<Store>()
              .Name("gridStores")
              .Columns(columns =>
              {
                  columns.Bound(c => c.Name).Title("Name").Filterable(c => c.CheckAll(true).Multi(true));
                  columns.Bound(c => c.Phone1).Title("Phone").Filterable(false);
                  columns.Bound(c => c.Email).Width(100).Filterable(false);
                  columns.Bound(c => c.ContactPerson).Width(150).Filterable(false);
                  columns.Bound(c => c.City).Width(100).Filterable(c => c.CheckAll(true).Multi(true));
                  columns.Command(command =>
                  {
                      command.Custom("editItem").Text("Edit").Click("function(e){ actionOnRowItem(e, '#gridStores', 'StoreId', '" + Url.Action("Edit", "Stores") + "');}");
                      command.Custom("viewItem").Text("Details").Click("function(e){ actionOnRowItem(e, '#gridStores', 'StoreId', '" + Url.Action("Details", "Stores") + "');}");
                      command.Custom("deleteItem").Text("Delete").Click("function(e){ actionOnRowItem(e, '#gridStores', 'StoreId', '" + Url.Action("Delete", "Stores") + "');}");
                  }).Title("Actions").Width(230);
              })
              .Resizable(c => c.Columns(true))
              .Selectable(s => s.Enabled(true).Mode(GridSelectionMode.Single))
              .Sortable(true)
              .Filterable(f => f.Enabled(true).Mode(GridFilterMode.Menu))
              .Groupable(false)
              .Pageable(p => p.Enabled(true).PageSizes(true))
              .Events(e => e.DataBound("onDataBoundGridTemplate"))
              .BindTo(Model.ToList())
              .DataSource(dataSource => dataSource
              .Ajax()
              .PageSize(10)
              .Batch(true)
              .ServerOperation(false)
              .Events(events => events.Error("error_handler"))
              .Model(model =>
              {
                  model.Id(p => p.StoreId);
                  model.Field(f => f.Name);
                  model.Field(f => f.Address);
                  model.Field(f => f.City);
                  model.Field(f => f.ContactPerson);
                  model.Field(f => f.Email);
                  model.Field(f => f.Phone1);
              })))
<script>
    $("#menu").find("li").removeClass("k-state-selected");
    $("#StoreMenuLink").addClass("k-state-selected");
</script>